name: Build

on:
  push:
    branches:
      - master  # or main if that's your default

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest  # ✅ use Linux runner!

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: SonarSource/sonarqube-scan-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
